import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Zilla_Slab } from "next/font/google";
import "./globals.css";

const zillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["400", "700"], // Customize as per need
  variable: "--font-zilla-slab", // Variable for easy swapping in CSS
  display: "swap",
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // customize as needed
  variable: '--poppins',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vineet Kushwaha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${zillaSlab.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
